### POST request to create user
POST http://localhost:9193/api/v1/users/create-user
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Password123!"
}

> {%
    client.global.set("userId", response.body.data.id);
    client.global.set("userEmail", response.body.data.email);
    client.global.set("password", request.body.password);
    client.global.set("firstName", response.body.data.firstName);
    client.global.set("lastName", response.body.data.lastName);
%}

###