name: CI / CD

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # needed later when we push the Docker image to GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: e-shop-api-scalable-e-commerce-backend  # lowercase only

jobs:
  build_and_test:
    name: Build & Test (Maven)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make Maven wrapper executable (Linux)
        run: chmod +x mvnw

      - name: Build & run tests
        run: ./mvnw -B -ntp clean verify

      - name: Upload test reports (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

  docker_build:
    name: Docker Build & Push
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:ci-${{ github.run_number }}